general_settings:
  drop_params: true
model_list:
- litellm_params:
    api_key: os.environ/GEMINI_API_KEY
    model: gemini/gemini-3.1-flash-lite
  model_name: gemini/gemini-3.1-flash-lite
- litellm_params:
    api_key: os.environ/GEMINI_API_KEY
    model: gemini/gemini-embedding-001
  model_name: gemini/gemini-embedding-001
